### ISSUE TITLE
StatusCode 404 functions logs table does not exist

### ISSUE THREAD

**Issue by hforeste** [Azure/azure-functions-performance-test#45]
In the new functions runtime, 1.0, function log table is not created until a function is executed.
Serverless benchmark tool will fail function log cleanup (only for function apps who had zero function executions) since the table does not exist yet hence 404.

**Comment by moumita11** [comment]
How can I stop getting these emails

Sent from my iPhone

On Nov 17, 2016, at 9:46 AM, Hawk Foreste <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #45<https://github.com/Azure/azure-functions-performance-test/issues/45>.

-

**Comment by hforeste** [comment]
Go to the repo home page and hover over unwatch and click ignoring. Sorry you've been receiving them

![image](https://cloud.githubusercontent.com/assets/917998/20408138/0db1acfe-acc9-11e6-89db-0abd58abf7ef.png)
